.PHONY: all

all: TrustRegion SubSolver EigenSolver

TrustRegion: TrustRegion.cpp
	$(CXX) -o ../../obj/TrustRegion.o TrustRegion.cpp -c $(Flags)

SubSolver: SubSolver.cpp
	$(CXX) -o ../../obj/SubSolver.o SubSolver.cpp -c $(Flags)

EigenSolver: EigenSolver.cpp
	$(CXX) -o ../../obj/EigenSolver.o EigenSolver.cpp -c $(Flags)
