.PHONY: all

all: TrustRegion SubSolver HessUpdate

TrustRegion: TrustRegion.cpp
	$(CXX) -o ../../obj/TrustRegion.o TrustRegion.cpp -c $(Flags)

SubSolver: SubSolver.cpp
	$(CXX) -o ../../obj/SubSolver.o SubSolver.cpp -c $(Flags)

HessUpdate: HessUpdate.cpp
	$(CXX) -o ../../obj/HessUpdate.o HessUpdate.cpp -c $(Flags)
