.PHONY: all

all: TrustRegion SubSolver HessUpdate

TrustRegion: TrustRegion.cpp
	$(CXX) -o ../../obj/$(LANG)TrustRegion.o TrustRegion.cpp -c $(Flags)

SubSolver: SubSolver.cpp
	$(CXX) -o ../../obj/$(LANG)SubSolver.o SubSolver.cpp -c $(Flags)

HessUpdate: HessUpdate.cpp
	$(CXX) -o ../../obj/$(LANG)HessUpdate.o HessUpdate.cpp -c $(Flags)
